// AUTO-GENERATED from chhattisgarh_statewide_summary.json — DO NOT EDIT DIRECTLY

export interface DistrictSummary {
  rank: number;
  name: string;
  zone: string;
  zone_code: 'hills' | 'plains' | 'plateau';
  predominant_soil: string;
  soil_order: string;
  vernacular_soil: 'Kanhar' | 'Dorsa' | 'Matasi' | 'Bhata';
  total_area_ha: number;
  bare_soil_ha: number;
  bare_soil_pct: number;
  mean_soc_deficiency: number;
  max_soc_deficiency: number;
  high_risk_ha: number;
  pct_high_risk: number;
  mean_soc_dg_kg: number;
  mean_clay_g_kg: number;
  mean_ph: number;
  mean_bsi: number;
  urgency_level: string;
  primary_advisory: string;
  secondary_advisory: string;
  full_advisory_package: string;
}

export interface StatewideAggregates {
  total_area_ha: number;
  bare_soil_ha: number;
  statewide_mean_soc_deficiency: number;
  high_risk_soc_deficit_ha: number;
  pct_high_risk_bare_soil: number;
}

export interface ZoneSummary {
  zone_name: string;
  district_count: number;
  total_area_ha: number;
  bare_soil_ha: number;
  mean_soc_deficiency: number;
  high_risk_ha: number;
  pct_high_risk: number;
  mean_soc_dg_kg: number;
  mean_clay_g_kg: number;
  mean_ph: number;
}

export const STATEWIDE_AGGREGATES: StatewideAggregates = {
  "total_area_ha": 13857000.0,
  "bare_soil_ha": 5485404.44,
  "statewide_mean_soc_deficiency": 0.4616,
  "high_risk_soc_deficit_ha": 243241.95,
  "pct_high_risk_bare_soil": 4.43
};

export const AGRO_CLIMATIC_ZONES: Record<string, ZoneSummary> = {
  "hills": {
    "zone_name": "Northern Hills Zone",
    "district_count": 7,
    "total_area_ha": 2965100.0,
    "bare_soil_ha": 1165720.55,
    "mean_soc_deficiency": 0.4499,
    "high_risk_ha": 8964.43,
    "pct_high_risk": 0.77,
    "mean_soc_dg_kg": 89.74,
    "mean_clay_g_kg": 183.95,
    "mean_ph": 5.56
  },
  "plains": {
    "zone_name": "Central Chhattisgarh Plains",
    "district_count": 19,
    "total_area_ha": 6702800.0,
    "bare_soil_ha": 2668812.26,
    "mean_soc_deficiency": 0.4758,
    "high_risk_ha": 217981.17,
    "pct_high_risk": 8.17,
    "mean_soc_dg_kg": 106.74,
    "mean_clay_g_kg": 308.06,
    "mean_ph": 6.76
  },
  "plateau": {
    "zone_name": "Bastar Plateau / Southern Zone",
    "district_count": 7,
    "total_area_ha": 4189100.0,
    "bare_soil_ha": 1650871.63,
    "mean_soc_deficiency": 0.4497,
    "high_risk_ha": 16296.35,
    "pct_high_risk": 0.99,
    "mean_soc_dg_kg": 91.45,
    "mean_clay_g_kg": 186.08,
    "mean_ph": 5.5
  }
};

export const DISTRICTS: DistrictSummary[] = [
  {
    rank: 1,
    name: "Bemetara",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Kanhar (Clay Vertisols)",
    soil_order: "Vertisols",
    vernacular_soil: "Kanhar",
    total_area_ha: 285500.0,
    bare_soil_ha: 111902.44,
    bare_soil_pct: 39.2,
    mean_soc_deficiency: 0.5224,
    max_soc_deficiency: 0.9354,
    high_risk_ha: 26190.58,
    pct_high_risk: 23.4,
    mean_soc_dg_kg: 110.49,
    mean_clay_g_kg: 416.25,
    mean_ph: 7.47,
    mean_bsi: 0.2417,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage.",
    secondary_advisory: "Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation.",
    full_advisory_package: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage. | Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation."
  },
  {
    rank: 2,
    name: "Kabirdham",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Kanhar (Clay Vertisols) & Dorsa (Inceptisols)",
    soil_order: "Vertisols",
    vernacular_soil: "Kanhar",
    total_area_ha: 444700.0,
    bare_soil_ha: 175828.04,
    bare_soil_pct: 39.54,
    mean_soc_deficiency: 0.5218,
    max_soc_deficiency: 0.9168,
    high_risk_ha: 40306.37,
    pct_high_risk: 22.92,
    mean_soc_dg_kg: 111.47,
    mean_clay_g_kg: 376.22,
    mean_ph: 7.17,
    mean_bsi: 0.2419,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage.",
    secondary_advisory: "Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation.",
    full_advisory_package: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage. | Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation."
  },
  {
    rank: 3,
    name: "Baloda Bazar-Bhatapara",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Kanhar (Clay Vertisols) & Matasi (Alfisols)",
    soil_order: "Vertisols",
    vernacular_soil: "Kanhar",
    total_area_ha: 373400.0,
    bare_soil_ha: 147078.67,
    bare_soil_pct: 39.39,
    mean_soc_deficiency: 0.5217,
    max_soc_deficiency: 0.9362,
    high_risk_ha: 33399.52,
    pct_high_risk: 22.71,
    mean_soc_dg_kg: 106.51,
    mean_clay_g_kg: 356.22,
    mean_ph: 7.27,
    mean_bsi: 0.2418,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage.",
    secondary_advisory: "Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation.",
    full_advisory_package: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage. | Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation."
  },
  {
    rank: 4,
    name: "Mungeli",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Kanhar (Clay Vertisols) & Dorsa (Inceptisols)",
    soil_order: "Vertisols",
    vernacular_soil: "Kanhar",
    total_area_ha: 275000.0,
    bare_soil_ha: 108181.38,
    bare_soil_pct: 39.34,
    mean_soc_deficiency: 0.5212,
    max_soc_deficiency: 0.9364,
    high_risk_ha: 24576.95,
    pct_high_risk: 22.72,
    mean_soc_dg_kg: 109.42,
    mean_clay_g_kg: 366.13,
    mean_ph: 7.27,
    mean_bsi: 0.242,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage.",
    secondary_advisory: "Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation.",
    full_advisory_package: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage. | Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation."
  },
  {
    rank: 5,
    name: "Durg",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Kanhar (Clay Vertisols)",
    soil_order: "Vertisols",
    vernacular_soil: "Kanhar",
    total_area_ha: 223800.0,
    bare_soil_ha: 87616.53,
    bare_soil_pct: 39.15,
    mean_soc_deficiency: 0.5209,
    max_soc_deficiency: 0.9388,
    high_risk_ha: 19943.12,
    pct_high_risk: 22.76,
    mean_soc_dg_kg: 117.48,
    mean_clay_g_kg: 426.15,
    mean_ph: 7.37,
    mean_bsi: 0.2415,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage.",
    secondary_advisory: "Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation.",
    full_advisory_package: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage. | Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation."
  },
  {
    rank: 6,
    name: "Raipur",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Kanhar (Clay Vertisols) & Dorsa (Inceptisols)",
    soil_order: "Vertisols",
    vernacular_soil: "Kanhar",
    total_area_ha: 289200.0,
    bare_soil_ha: 141585.13,
    bare_soil_pct: 48.96,
    mean_soc_deficiency: 0.4932,
    max_soc_deficiency: 1.0,
    high_risk_ha: 33907.88,
    pct_high_risk: 23.95,
    mean_soc_dg_kg: 111.94,
    mean_clay_g_kg: 292.85,
    mean_ph: 5.55,
    mean_bsi: 0.218,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage.",
    secondary_advisory: "Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation.",
    full_advisory_package: "Vertisol Structure Maintenance: Adopt Integrated Nutrient Management (75% RDF + 25% organic manure) + Green Manuring (Dhaincha/Sesbania aculeata) prior to puddling + reduced tillage. | Apply Gypsum @ 2.0 t/ha to relieve clay sodicity, stimulate aeration, and enhance humic clay-organic complexation. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.55) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 7,
    name: "Gaurela-Pendra-Marwahi",
    zone: "Northern Hills Zone",
    zone_code: "hills",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Bhata (Entisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 230700.0,
    bare_soil_ha: 91011.32,
    bare_soil_pct: 39.45,
    mean_soc_deficiency: 0.4572,
    max_soc_deficiency: 0.8039,
    high_risk_ha: 1904.43,
    pct_high_risk: 2.09,
    mean_soc_dg_kg: 92.47,
    mean_clay_g_kg: 196.09,
    mean_ph: 5.77,
    mean_bsi: 0.2418,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.77) and unlock microbial organic carbon mineralization.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.77) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 8,
    name: "Janjgir-Champa",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Kanhar (Vertisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 242200.0,
    bare_soil_ha: 94916.12,
    bare_soil_pct: 39.19,
    mean_soc_deficiency: 0.4572,
    max_soc_deficiency: 0.8306,
    high_risk_ha: 2036.32,
    pct_high_risk: 2.15,
    mean_soc_dg_kg: 114.43,
    mean_clay_g_kg: 336.06,
    mean_ph: 6.87,
    mean_bsi: 0.2414,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 9,
    name: "Mahasamund",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Dorsa (Inceptisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 479000.0,
    bare_soil_ha: 188161.87,
    bare_soil_pct: 39.28,
    mean_soc_deficiency: 0.4572,
    max_soc_deficiency: 0.8244,
    high_risk_ha: 4041.85,
    pct_high_risk: 2.15,
    mean_soc_dg_kg: 100.42,
    mean_clay_g_kg: 236.05,
    mean_ph: 6.47,
    mean_bsi: 0.2427,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion."
  },
  {
    rank: 10,
    name: "Gariaband",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Bhata (Entisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 582300.0,
    bare_soil_ha: 230108.72,
    bare_soil_pct: 39.52,
    mean_soc_deficiency: 0.4572,
    max_soc_deficiency: 0.8185,
    high_risk_ha: 5393.31,
    pct_high_risk: 2.34,
    mean_soc_dg_kg: 98.49,
    mean_clay_g_kg: 216.22,
    mean_ph: 6.17,
    mean_bsi: 0.2414,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion."
  },
  {
    rank: 11,
    name: "Surguja",
    zone: "Northern Hills Zone",
    zone_code: "hills",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Bhata (Entisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 573200.0,
    bare_soil_ha: 226495.17,
    bare_soil_pct: 39.51,
    mean_soc_deficiency: 0.4571,
    max_soc_deficiency: 0.8149,
    high_risk_ha: 4434.39,
    pct_high_risk: 1.96,
    mean_soc_dg_kg: 96.45,
    mean_clay_g_kg: 200.97,
    mean_ph: 5.67,
    mean_bsi: 0.2422,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.67) and unlock microbial organic carbon mineralization.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.67) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 12,
    name: "Balod",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Matasi (Alfisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 352700.0,
    bare_soil_ha: 138290.09,
    bare_soil_pct: 39.21,
    mean_soc_deficiency: 0.4571,
    max_soc_deficiency: 0.8173,
    high_risk_ha: 2868.49,
    pct_high_risk: 2.07,
    mean_soc_dg_kg: 104.45,
    mean_clay_g_kg: 276.07,
    mean_ph: 6.67,
    mean_bsi: 0.2422,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 13,
    name: "Korba",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Dorsa (Inceptisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 714500.0,
    bare_soil_ha: 281587.31,
    bare_soil_pct: 39.41,
    mean_soc_deficiency: 0.457,
    max_soc_deficiency: 0.7913,
    high_risk_ha: 5505.71,
    pct_high_risk: 1.96,
    mean_soc_dg_kg: 101.43,
    mean_clay_g_kg: 246.07,
    mean_ph: 6.37,
    mean_bsi: 0.2416,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion."
  },
  {
    rank: 14,
    name: "Dhamtari",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Matasi (Alfisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 408100.0,
    bare_soil_ha: 160603.44,
    bare_soil_pct: 39.35,
    mean_soc_deficiency: 0.4569,
    max_soc_deficiency: 0.8268,
    high_risk_ha: 3325.28,
    pct_high_risk: 2.07,
    mean_soc_dg_kg: 107.44,
    mean_clay_g_kg: 265.93,
    mean_ph: 6.57,
    mean_bsi: 0.2419,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 15,
    name: "Khairagarh-Chhuikhadan-Gandai",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Kanhar (Vertisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 300400.0,
    bare_soil_ha: 117953.39,
    bare_soil_pct: 39.27,
    mean_soc_deficiency: 0.4569,
    max_soc_deficiency: 0.8112,
    high_risk_ha: 2397.3,
    pct_high_risk: 2.03,
    mean_soc_dg_kg: 105.45,
    mean_clay_g_kg: 316.1,
    mean_ph: 6.87,
    mean_bsi: 0.2417,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 16,
    name: "Surajpur",
    zone: "Northern Hills Zone",
    zone_code: "hills",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Dorsa (Inceptisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 278700.0,
    bare_soil_ha: 109721.97,
    bare_soil_pct: 39.37,
    mean_soc_deficiency: 0.4568,
    max_soc_deficiency: 0.8153,
    high_risk_ha: 2368.71,
    pct_high_risk: 2.16,
    mean_soc_dg_kg: 94.47,
    mean_clay_g_kg: 216.23,
    mean_ph: 5.77,
    mean_bsi: 0.2423,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.77) and unlock microbial organic carbon mineralization.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.77) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 17,
    name: "Raigarh",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Matasi (Alfisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 468900.0,
    bare_soil_ha: 185181.73,
    bare_soil_pct: 39.49,
    mean_soc_deficiency: 0.4567,
    max_soc_deficiency: 0.8132,
    high_risk_ha: 4006.71,
    pct_high_risk: 2.16,
    mean_soc_dg_kg: 103.45,
    mean_clay_g_kg: 276.06,
    mean_ph: 6.57,
    mean_bsi: 0.2415,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 18,
    name: "Bastar",
    zone: "Bastar Plateau / Southern Zone",
    zone_code: "plateau",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Bhata (Entisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 659700.0,
    bare_soil_ha: 261037.3,
    bare_soil_pct: 39.57,
    mean_soc_deficiency: 0.4566,
    max_soc_deficiency: 0.818,
    high_risk_ha: 5103.58,
    pct_high_risk: 1.96,
    mean_soc_dg_kg: 94.42,
    mean_clay_g_kg: 196.18,
    mean_ph: 5.57,
    mean_bsi: 0.2414,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.57) and unlock microbial organic carbon mineralization.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.57) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 19,
    name: "Bilaspur",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Kanhar (Vertisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 351800.0,
    bare_soil_ha: 139139.65,
    bare_soil_pct: 39.55,
    mean_soc_deficiency: 0.4566,
    max_soc_deficiency: 0.8246,
    high_risk_ha: 2737.7,
    pct_high_risk: 1.97,
    mean_soc_dg_kg: 107.49,
    mean_clay_g_kg: 326.23,
    mean_ph: 6.97,
    mean_bsi: 0.2419,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 20,
    name: "Kondagaon",
    zone: "Bastar Plateau / Southern Zone",
    zone_code: "plateau",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Bhata (Entisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 776900.0,
    bare_soil_ha: 306179.4,
    bare_soil_pct: 39.41,
    mean_soc_deficiency: 0.4566,
    max_soc_deficiency: 0.8144,
    high_risk_ha: 6543.71,
    pct_high_risk: 2.14,
    mean_soc_dg_kg: 92.43,
    mean_clay_g_kg: 186.13,
    mean_ph: 5.67,
    mean_bsi: 0.2413,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.67) and unlock microbial organic carbon mineralization.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.67) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 21,
    name: "Sarangarh-Bilaigarh",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Kanhar (Vertisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 245800.0,
    bare_soil_ha: 97039.54,
    bare_soil_pct: 39.48,
    mean_soc_deficiency: 0.4565,
    max_soc_deficiency: 0.8213,
    high_risk_ha: 1965.32,
    pct_high_risk: 2.03,
    mean_soc_dg_kg: 110.41,
    mean_clay_g_kg: 326.09,
    mean_ph: 6.97,
    mean_bsi: 0.2415,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 22,
    name: "Sakti",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 144700.0,
    bare_soil_ha: 57318.3,
    bare_soil_pct: 39.61,
    mean_soc_deficiency: 0.4564,
    max_soc_deficiency: 0.8023,
    high_risk_ha: 1121.64,
    pct_high_risk: 1.96,
    mean_soc_dg_kg: 108.45,
    mean_clay_g_kg: 306.17,
    mean_ph: 6.77,
    mean_bsi: 0.2417,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 23,
    name: "Rajnandgaon",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Dorsa (Loam Inceptisols) & Matasi (Alfisols)",
    soil_order: "Inceptisols",
    vernacular_soil: "Dorsa",
    total_area_ha: 306200.0,
    bare_soil_ha: 121637.13,
    bare_soil_pct: 39.72,
    mean_soc_deficiency: 0.4564,
    max_soc_deficiency: 0.8144,
    high_risk_ha: 2518.34,
    pct_high_risk: 2.07,
    mean_soc_dg_kg: 102.48,
    mean_clay_g_kg: 286.22,
    mean_ph: 6.77,
    mean_bsi: 0.2416,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Balanced Loam Management: Apply 5-6 t/ha FYM + relay cropping of pulses (Urd/Mung) in standing paddy + reduced tillage."
  },
  {
    rank: 24,
    name: "Mohla-Manpur-Ambagarh Chowki",
    zone: "Central Chhattisgarh Plains",
    zone_code: "plains",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Bhata (Entisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 214600.0,
    bare_soil_ha: 84682.78,
    bare_soil_pct: 39.46,
    mean_soc_deficiency: 0.4563,
    max_soc_deficiency: 0.8179,
    high_risk_ha: 1738.78,
    pct_high_risk: 2.05,
    mean_soc_dg_kg: 96.45,
    mean_clay_g_kg: 206.01,
    mean_ph: 6.27,
    mean_bsi: 0.2425,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion."
  },
  {
    rank: 25,
    name: "Kanker",
    zone: "Bastar Plateau / Southern Zone",
    zone_code: "plateau",
    predominant_soil: "Matasi (Sandy Loam Alfisols) & Dorsa (Inceptisols)",
    soil_order: "Alfisols",
    vernacular_soil: "Matasi",
    total_area_ha: 528500.0,
    bare_soil_ha: 208171.07,
    bare_soil_pct: 39.39,
    mean_soc_deficiency: 0.4561,
    max_soc_deficiency: 0.8226,
    high_risk_ha: 4112.78,
    pct_high_risk: 1.98,
    mean_soc_dg_kg: 99.48,
    mean_clay_g_kg: 226.04,
    mean_ph: 5.97,
    mean_bsi: 0.2417,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion.",
    secondary_advisory: "Cover cropping with local legumes.",
    full_advisory_package: "Alfisol Humus Building: Apply 8-10 t/ha FYM + 2-3 t/ha Biochar + contour bunding & vegetative barriers (Vetiver grass) to conserve moisture and arrest slope erosion."
  },
  {
    rank: 26,
    name: "Narayanpur",
    zone: "Bastar Plateau / Southern Zone",
    zone_code: "plateau",
    predominant_soil: "Bhata (Gravelly Red Entisols) & Forest Inceptisols",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 664000.0,
    bare_soil_ha: 262515.87,
    bare_soil_pct: 39.54,
    mean_soc_deficiency: 0.4449,
    max_soc_deficiency: 0.6162,
    high_risk_ha: 172.24,
    pct_high_risk: 0.07,
    mean_soc_dg_kg: 91.46,
    mean_clay_g_kg: 180.97,
    mean_ph: 5.47,
    mean_bsi: 0.2415,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.47) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 27,
    name: "Bijapur",
    zone: "Bastar Plateau / Southern Zone",
    zone_code: "plateau",
    predominant_soil: "Bhata (Gravelly Red Entisols) & Red Sandy Alfisols",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 655300.0,
    bare_soil_ha: 257576.42,
    bare_soil_pct: 39.31,
    mean_soc_deficiency: 0.4448,
    max_soc_deficiency: 0.6598,
    high_risk_ha: 139.99,
    pct_high_risk: 0.05,
    mean_soc_dg_kg: 87.46,
    mean_clay_g_kg: 171.01,
    mean_ph: 5.37,
    mean_bsi: 0.2423,
    urgency_level: "CRITICAL (TIER 1)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.37) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 28,
    name: "Jashpur",
    zone: "Northern Hills Zone",
    zone_code: "hills",
    predominant_soil: "Bhata (Gravelly Red Entisols) & Lateritic Alfisols",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 620500.0,
    bare_soil_ha: 240631.22,
    bare_soil_pct: 38.78,
    mean_soc_deficiency: 0.4448,
    max_soc_deficiency: 0.6512,
    high_risk_ha: 75.74,
    pct_high_risk: 0.03,
    mean_soc_dg_kg: 90.5,
    mean_clay_g_kg: 176.19,
    mean_ph: 5.37,
    mean_bsi: 0.2415,
    urgency_level: "MODERATE (TIER 2)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.37) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 29,
    name: "Koriya",
    zone: "Northern Hills Zone",
    zone_code: "hills",
    predominant_soil: "Bhata (Gravelly Red Entisols) & Matasi (Alfisols)",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 237800.0,
    bare_soil_ha: 94313.01,
    bare_soil_pct: 39.66,
    mean_soc_deficiency: 0.4446,
    max_soc_deficiency: 0.654,
    high_risk_ha: 65.31,
    pct_high_risk: 0.07,
    mean_soc_dg_kg: 87.43,
    mean_clay_g_kg: 171.11,
    mean_ph: 5.47,
    mean_bsi: 0.2415,
    urgency_level: "CRITICAL (TIER 1)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.47) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 30,
    name: "Sukma",
    zone: "Bastar Plateau / Southern Zone",
    zone_code: "plateau",
    predominant_soil: "Bhata (Gravelly Red Entisols) & Red Sandy Alfisols",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 563600.0,
    bare_soil_ha: 222185.82,
    bare_soil_pct: 39.42,
    mean_soc_deficiency: 0.4445,
    max_soc_deficiency: 0.6269,
    high_risk_ha: 172.0,
    pct_high_risk: 0.08,
    mean_soc_dg_kg: 86.45,
    mean_clay_g_kg: 166.05,
    mean_ph: 5.17,
    mean_bsi: 0.2416,
    urgency_level: "CRITICAL (TIER 1)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 2.0 t/ha to optimize soil pH (currently 5.17) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 31,
    name: "Balrampur-Ramanujganj",
    zone: "Northern Hills Zone",
    zone_code: "hills",
    predominant_soil: "Bhata (Gravelly Red Entisols)",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 601600.0,
    bare_soil_ha: 237212.3,
    bare_soil_pct: 39.43,
    mean_soc_deficiency: 0.4443,
    max_soc_deficiency: 0.5997,
    high_risk_ha: 64.26,
    pct_high_risk: 0.03,
    mean_soc_dg_kg: 82.4,
    mean_clay_g_kg: 160.88,
    mean_ph: 5.27,
    mean_bsi: 0.2416,
    urgency_level: "CRITICAL (TIER 1)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 2.0 t/ha to optimize soil pH (currently 5.27) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 32,
    name: "Dantewada",
    zone: "Bastar Plateau / Southern Zone",
    zone_code: "plateau",
    predominant_soil: "Bhata (Gravelly Red Entisols) & Lateritic Alfisols",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 341100.0,
    bare_soil_ha: 133205.75,
    bare_soil_pct: 39.05,
    mean_soc_deficiency: 0.4443,
    max_soc_deficiency: 0.6021,
    high_risk_ha: 52.05,
    pct_high_risk: 0.04,
    mean_soc_dg_kg: 88.43,
    mean_clay_g_kg: 176.17,
    mean_ph: 5.27,
    mean_bsi: 0.2417,
    urgency_level: "CRITICAL (TIER 1)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 2.0 t/ha to optimize soil pH (currently 5.27) and unlock microbial organic carbon mineralization."
  },
  {
    rank: 33,
    name: "Manendragarh-Chirmiri-Bharatpur",
    zone: "Northern Hills Zone",
    zone_code: "hills",
    predominant_soil: "Bhata (Gravelly Red Entisols)",
    soil_order: "Entisols",
    vernacular_soil: "Bhata",
    total_area_ha: 422600.0,
    bare_soil_ha: 166335.56,
    bare_soil_pct: 39.36,
    mean_soc_deficiency: 0.4442,
    max_soc_deficiency: 0.6961,
    high_risk_ha: 51.59,
    pct_high_risk: 0.03,
    mean_soc_dg_kg: 84.48,
    mean_clay_g_kg: 166.17,
    mean_ph: 5.57,
    mean_bsi: 0.2424,
    urgency_level: "CRITICAL (TIER 1)",
    primary_advisory: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning.",
    secondary_advisory: "Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers.",
    full_advisory_package: "Critical Skeletal Topsoil Restoration: Apply 12-15 t/ha FYM + 4-5 t/ha Biochar to rebuild permanent cation exchange capacity (CEC) + enforce 100% crop residue retention with zero burning. | Erosion Control & Watershed Buffering: Implement continuous hillside contour bunding, stone terracing, and agroforestry integration with Millets (Kodo-Kutki) and perennial legume buffers. | Acidic Reaction Neutralization: Apply Agricultural Lime @ 1.5 t/ha to optimize soil pH (currently 5.57) and unlock microbial organic carbon mineralization."
  },
];
